openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    RESTful API for managing user contacts. Supports CRUD operations, filtering, 
    pagination, and secure authentication via JWT. Designed for seamless integration 
    with frontend applications and third-party services.
tags:
  - name: Contacts
    description: Endpoints for managing user contacts.

  - name: Auth
    description: Registration, login, logout

servers:
  - url: http://localhost:3000
    description: development

  - url: https://nodejs-hw-mongodb-rr01.onrender.com
    description: production

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
